services:
   wrt-ubuntu22.04:
    build:
      context: ./
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"
    environment:
      - TZ=America/Los_Angeles
      - DEBIAN_FRONTEND=noninteractive
    privileged: true
    stdin_open: true
    tty: true
    image: wrt-ubuntu22.04:latest
    container_name:  wrt-ubuntu22.04
    volumes:
      - openwrt-ccache:/home/ccache
volumes:
  openwrt-ccache:
