services:
   buildroot-dev:
    environment:
      - APPLY_CONFIGS
      - CLEAN_AFTER_BUILD
      - ENV_FILES
      - EXIT_AFTER_BUILD
      - NO_BUILD
      - VERBOSE
    build:
      context: ./
      args:
        BUILDROOT_USER: br-user
        BUILDROOT_DIR: buildroot
        BUILDROOT_VERSION: 2025.02
        # BUILDROOT_VERSION: git
        # BUILDROOT_BRANCH: master
        # Space deliminated list of external trees of which to use.
        EXTERNAL_TREES: external
        # BUILDROOT_PATCH_DIR: "external/patches/buildroot/"
        UID: 1000
        GID: 1000
      ulimits:
        nofile:
          soft: 65536
          hard: 65536
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - ./:/mnt
      - example-buildroot-project-build-ccache:/home/ccache
    image: example-buildroot-project-build:latest
    container_name:  example-buildroot-project-build
volumes:
  example-buildroot-project-build-ccache:
